import Head from "next/head";
import { useRouter } from "next/dist/client/router";
import { useEffect } from "react";
import { colors } from "../styles/theme";
import Button from "../components/Button";
import Github from "../components/icons/Github";
import { loginWithGithub } from "../firebase/client";
import useUser, { USER_STATES } from "../hooks/useUser";

export default function Home() {
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    user && router.replace("/home");
  }, [user]);

  const handleClick = () => {
    loginWithGithub().catch(console.log);
  };

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <section>
        <img src="/twitter-logo-dark.svg" alt="Twitter Logo" />
        <h1>Twitter!</h1>
        <h2>
          Talk about development <br /> with developers 👨‍💻 👩‍💻
        </h2>
        {user === USER_STATES.NOT_LOGGED && (
          <div>
            <Button onClick={handleClick}>
              <Github fill="#fff" />
              Login with Github
            </Button>
          </div>
        )}
        {user === USER_STATES.NOT_KNOWN && (
          <img src="/spinner.gif" alt="spinner" />
        )}
      </section>

      <style jsx>
        {`
          img {
            width: 120px;
          }

          div {
            margin-top: 16px;
          }

          section {
            display: grid;
            height: 100%;
            place-content: center;
            place-items: center;
          }

          h1 {
            color: ${colors.primary};
            font-size: 24px;
            font-weight: 800;
            margin-bottom: 0;
          }

          h2 {
            color: ${colors.secondary};
            font-size: 18px;
            margin: 0;
          }
        `}
      </style>
    </>
  );
}
