import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";
import Tweet from "../../components/Tweet";
import { listenLatestTweets } from "../../firebase/client";
import useUser from "../../hooks/useUser";
import Create from "../../components/Icons/Create";
import Home from "../../components/Icons/Home";
import Search from "../../components/Icons/Search";
import { colors } from "../../styles/theme";

export default function HomePage() {
  const [timeline, setTimeLine] = useState([]);
  const user = useUser();

  useEffect(() => {
    let unsuscribe;
    if (user) {
      unsuscribe = listenLatestTweets(setTimeLine);
    }
    return () => unsuscribe && unsuscribe();
  }, [user]);

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <div>
        <header>
          <h2>Inicio</h2>
        </header>
        <section>
          {timeline.map((tweet) => (
            <Tweet
              avatar={tweet.avatar}
              createdAt={tweet.createdAt}
              content={tweet.content}
              id={tweet.id}
              img={tweet.img}
              key={tweet.id}
              userName={tweet.userName}
              userId={tweet.userId}
            />
          ))}
        </section>
        <nav>
          <Link href="/home">
            <a>
              <Home width={32} height={32} stroke="#89f" />
            </a>
          </Link>
          <Link href="/search">
            <a>
              <Search width={32} height={32} stroke="#89f" />
            </a>
          </Link>
          <Link href="/compose/tweet">
            <a>
              <Create width={32} height={32} stroke="#89f" />
            </a>
          </Link>
        </nav>
      </div>

      <style jsx>{`
        header {
          align-items: center;
          background: #ffffffaa;
          backdrop-filter: blur(5px);
          border-bottom: 1px solid #eee;
          height: 49px;
          display: flex;
          position: sticky;
          top: 0;
          width: 100%;
        }

        section {
          flex: 1;
        }

        h2 {
          font-size: 21px;
          font-weight: 800;
          padding-left: 15px;
        }

        nav {
          background: #fff;
          border-top: 1px solid #eee;
          bottom: 0;
          display: flex;
          height: 49px;
          position: sticky;
          width: 100%;
        }

        nav a {
          align-items: center;
          display: flex;
          flex: 1 1 auto;
          height: 100%;
          justify-content: center;
        }

        nav a:hover {
          background: radial-gradient(#0099ff22 15%, transparent 16%);
          background-size: 180px 180px;
          background-position: center;
        }

        nav a:hover > :global(svg) {
          stroke: ${colors.primary};
        }
      `}</style>
    </>
  );
}
