import Head from "next/head";
import { useState } from "react";
import Button from "../../../components/Button";
import useUser from "../../../hooks/useUser";

import { addTweet } from "../../../firebase/client";
import { useRouter } from "next/dist/client/router";

const COMPOSE_STATUS = {
  USER_NOT_KNOWN: 0,
  LOADING: 1,
  SUCCESS: 2,
  ERROR: -1,
};

export default function ComposeTweet() {
  const [message, setMessage] = useState("");
  const [status, setStatus] = useState(COMPOSE_STATUS.USER_NOT_KNOWN);
  const user = useUser();
  const router = useRouter();

  const handleChange = (e) => {
    const { value } = e.target;
    setMessage(value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setStatus(COMPOSE_STATUS.LOADING);
    addTweet({
      avatar: user.avatar,
      content: message,
      userId: user.uid,
      userName: user.username,
    })
      .then(() => {
        router.push("/home");
      })
      .catch((error) => {
        setStatus(COMPOSE_STATUS.ERROR);
      });
  };

  const isButtonDisabled = !message.length || status === COMPOSE_STATUS.LOADING;

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <form onSubmit={handleSubmit}>
        <textarea
          onChange={handleChange}
          placeholder="¿Qué está pasando?"
          value={message}
        />
        <div>
          <Button type="submit" disabled={isButtonDisabled}>
            Twittear
          </Button>
        </div>
      </form>
      <style jsx>{`
        div {
          padding: 15px;
        }

        textarea {
          border: 0;
          font-size: 21px;
          min-height: 200px;
          outline: 0;
          padding: 15px;
          resize: none;
          width: 100%;
        }
      `}</style>
    </>
  );
}
